### ISSUE TITLE
Doesn't compile with latest commit on kernel 5.16.11

### ISSUE THREAD

**Issue by nursoda** [xmm7360/xmm7360-pci#170]
Using the [latest commit](https://github.com/xmm7360/xmm7360-pci/commit/5c56bc911bbd4716c7f2418d5c8a315e505c48c6) I see this on Arch, kernel 5.16.11

```
# make
make -C /lib/modules/5.16.11-arch1-1/build M=/workdir/xmm7360-pci modules
make[1]: Entering directory '/usr/lib/modules/5.16.11-arch1-1/build'
  CC [M]  /workdir/xmm7360-pci/xmm7360.o
/workdir/xmm7360-pci/xmm7360.c:1276:1: error: version control conflict marker in file
 1276 | <<<<<<< Updated upstream
      | ^~~~~~~
/workdir/xmm7360-pci/xmm7360.c:1331:23: error: 'xmm7360_tty_write_room' undeclared here (not in a function); did you mean 'xmm7360_tty_write'?
 1331 |         .write_room = xmm7360_tty_write_room,
      |                       ^~~~~~~~~~~~~~~~~~~~~~
      |                       xmm7360_tty_write
make[2]: *** [scripts/Makefile.build:287: /workdir/xmm7360-pci/xmm7360.o] Error 1
make[1]: *** [Makefile:1846: /workdir/xmm7360-pci] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.16.11-arch1-1/build'
make: *** [Makefile:9: default] Error 2
# 
```
