### PR TITLE
fix compiler warning with kernel version 6.6

### PR DESCRIPTION
**Pull request by mfournier**
I came across this warning after upgrading from kernel 6.5 to 6.6.
The issue seems pretty similar to #139.

```
/home/marc/src/xmm7360-pci/xmm7360.c:1342:18: error: initialization of ‘ssize_t (*)(struct tty_struct *, const u8 *, size_t)’ {aka ‘long int (*)(struct tty_struct *, const unsigned char *, long unsigned int)’} from incompatible pointer type ‘int (*)(struct tty_struct *, const unsigned char *, int)’ [-Werror=incompatible-pointer-types]
 1342 |         .write = xmm7360_tty_write,
      |                  ^~~~~~~~~~~~~~~~~
/home/marc/src/xmm7360-pci/xmm7360.c:1342:18: note: (near initialization for ‘xmm7360_tty_ops.write’)
```

This patch fixes what the compiler complains about, and lets xmm7360 build again.

### CODE REVIEW

**Comment by mfournier** [comment]
#215 and #219 are reporting this problem.

**Comment by ManDay** [comment]
Why are you not using `ssize_t` and `size_t` as the compiler demands?

**Comment by mfournier** [comment]
@ManDay thanks ! For no other reason than: I'm incapable of reading properly :facepalm: 
Updated in 3259b38.

**Comment by fasmide** [comment]
Just wanted to add these changes works on my machine :) 

```
Linux archlinux 6.9.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000 x86_64 GNU/Linux
```

**Comment by bondany** [comment]
> Just wanted to add these changes works on my machine :)
> 
> ```
> Linux archlinux 6.9.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000 x86_64 GNU/Linux
> ```

Works for me too. 👍
