### PR TITLE
Fix build in kernel v5.15 and later

### PR DESCRIPTION
**Pull request by hschauhan**
In kernel 5.15 and later tty_driver_kref_put is to be used as put_tty_driver has been removed.
Fix, the write_room function signature to return unsigned int as expected by tty_operations

### CODE REVIEW

**Comment by ko-pp** [comment]
Works for me on Void Linux with Linux 5.15.14 on a Lenovo ThinkPad T495s, thanks for the fix :)

**Comment by Figureix** [comment]
This fix also works on Pop!_OS with 5.15.11 on a ThinkPad X1 Yoga.

**Review by annejan — APPROVED** [review]
Seems tto work great, tested on OpenSUSE kernel 5.16.1

**Comment by MaxG-Enpal** [comment]
Is it possible to merge this one?

**Comment by tgxn** [comment]
Hey @hschauhan  Great works, thanks!

Just noticed that the pipelines are failing with the new `write_room` function.

```
/home/runner/work/xmm7360-pci/xmm7360-pci/xmm7360.c:1323:16: error: initialization of ‘int (*)(struct tty_struct *)’ from incompatible pointer type ‘unsigned int (*)(struct tty_struct *)’ [-Werror=incompatible-pointer-types]
 1323 |  .write_room = xmm7360_tty_write_room,
      |                ^~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/xmm7360-pci/xmm7360-pci/xmm7360.c:1323:16: note: (near initialization for ‘xmm7360_tty_ops.write_room’)
```

It's possible that this is due to the configuration for the runner's kernel.

**Comment by Mad-Mason** [comment]
Something like this should work. I've tried it using the latest master xmm7360.c on kernel 5.15.19 (Slackware 15.0) and it works as expected. I don't have an earlier kernel to try it on so needs more testing

---------------------
PATCH diif -Naur
---------------------

--- xmm7360.c.orig      2022-02-07 13:44:46.229144241 +0000
+++ xmm7360.c   2022-02-07 13:53:26.487733908 +0000
@@ -22,6 +22,7 @@
  * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
  */
 
+#include <linux/version.h>
 #include <linux/cdev.h>
 #include <linux/delay.h>
 #include <linux/hrtimer.h>
@@ -1272,7 +1273,11 @@
        return written;
 }
 
+#if LINUX_VERSION_CODE < KERNEL_VERSION(5,14,0)
 static int xmm7360_tty_write_room(struct tty_struct *tty)
+#else
+static unsigned int xmm7360_tty_write_room(struct tty_struct *tty)
+#endif
 {
        struct queue_pair *qp = tty->driver_data;
        if (!xmm7360_qp_can_write(qp))

**Comment by tgxn** [comment]
Changes were merged in individual PR's:
- https://github.com/xmm7360/xmm7360-pci/pull/139/files
- https://github.com/xmm7360/xmm7360-pci/pull/152/files

Closing this PR.
